import Foundation

/// A pasteboard observation, already read off NSPasteboard by the monitor.
/// Pure value so accept/classify decisions are unit-testable.
public struct ClipCandidate: Equatable, Sendable {
    public var text: String?
    public var imageData: Data?
    public var fileURLs: [URL]
    public var sourceBundleID: String?
    public var sourceAppName: String?
    /// org.nspasteboard.ConcealedType or AutoGeneratedType present.
    public var isConcealed: Bool
    /// org.nspasteboard.TransientType present.
    public var isTransient: Bool

    public init(
        text: String?, imageData: Data?, fileURLs: [URL], sourceBundleID: String?,
        sourceAppName: String?, isConcealed: Bool, isTransient: Bool
    ) {
        self.text = text
        self.imageData = imageData
        self.fileURLs = fileURLs
        self.sourceBundleID = sourceBundleID
        self.sourceAppName = sourceAppName
        self.isConcealed = isConcealed
        self.isTransient = isTransient
    }
}

/// Minimal shape `pruneUIDs` needs, so the rule tests need no SwiftData.
public protocol ClipPrunable {
    var uid: String { get }
    var createdAt: Date { get }
    var pinnedToShelf: Bool { get }
    var isFiled: Bool { get }
}

/// Pure capture/retention policy for the clipboard layer (spec §3–4).
public enum ClipStoreRules {
    /// Rolling history size (unpinned, unfiled clips only).
    public static let historyLimit = 200

    /// Bundle IDs whose copies are never recorded. Constants for now
    /// (editable config is out of scope per spec §7).
    public static let excludedBundleIDs: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7",
        "com.apple.keychainaccess", "com.apple.Passwords",
    ]

    public static func shouldCapture(_ candidate: ClipCandidate, latestPayload: String?) -> Bool {
        if candidate.isConcealed || candidate.isTransient { return false }
        if let bundle = candidate.sourceBundleID, excludedBundleIDs.contains(bundle) {
            return false
        }
        let trimmed = candidate.text?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let hasContent = !trimmed.isEmpty || candidate.imageData != nil
            || !candidate.fileURLs.isEmpty
        guard hasContent else { return false }
        if !trimmed.isEmpty, trimmed == latestPayload { return false }
        return true
    }

    /// UIDs to delete: oldest unpinned/unfiled clips beyond `limit`.
    public static func pruneUIDs<T: ClipPrunable>(_ clips: [T], limit: Int = historyLimit) -> [String] {
        let history = clips
            .filter { !$0.pinnedToShelf && !$0.isFiled }
            .sorted { $0.createdAt < $1.createdAt }
        let overflow = history.count - limit
        guard overflow > 0 else { return [] }
        return history.prefix(overflow).map(\.uid)
    }
}
