import Foundation

/// The slice of NSPasteboard the monitor needs, injectable for tests.
@MainActor
public protocol PasteboardReading: AnyObject {
    var changeCount: Int { get }
    /// Read the current pasteboard contents as a candidate (nil = unreadable).
    func readCandidate() -> ClipCandidate?
}

/// Watches the general pasteboard by polling `changeCount` (~1 s — the only
/// supported mechanism; Supaste/Helm norm). Emits candidates; all accept/skip
/// decisions live in `ClipStoreRules` downstream. Never blocks the main actor:
/// each poll is one changeCount compare, and reads happen only on change.
@MainActor
public final class ClipboardMonitor {
    private let pasteboard: PasteboardReading
    private let onCandidate: (ClipCandidate) -> Void
    private var lastChangeCount: Int
    private var ownWriteChangeCounts: Set<Int> = []
    private var timer: Timer?

    public init(pasteboard: PasteboardReading, onCandidate: @escaping (ClipCandidate) -> Void) {
        self.pasteboard = pasteboard
        self.onCandidate = onCandidate
        self.lastChangeCount = pasteboard.changeCount
    }

    /// The notch's own copy button writes the pasteboard; that write must not
    /// re-enter history. Call with the changeCount observed after writing.
    public func expectOwnWrite(changeCount: Int) {
        ownWriteChangeCounts.insert(changeCount)
    }

    public func start(interval: TimeInterval = 1.0) {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.pollOnce() }
        }
        timer.tolerance = 0.3
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    public func pollOnce() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        let matchedOwnWrite = ownWriteChangeCounts.remove(count) != nil
        // A real write can coalesce over an announced own-write count before
        // the next poll (we jump straight past it) — that mark is never
        // consumed by the exact match above, so sweep it here. Otherwise it
        // sits in the set forever and, if a count were ever revisited, could
        // wrongly swallow an unrelated later copy.
        if !ownWriteChangeCounts.isEmpty {
            ownWriteChangeCounts = ownWriteChangeCounts.filter { $0 > count }
        }
        if matchedOwnWrite { return }
        guard let candidate = pasteboard.readCandidate() else { return }
        onCandidate(candidate)
    }
}

#if os(macOS)
import AppKit

/// Live NSPasteboard adapter. Reads string/image/file-URL representations
/// and flags nspasteboard.org marker types so the rules can skip them.
@MainActor
public final class LivePasteboard: PasteboardReading {
    private let board = NSPasteboard.general
    public init() {}

    public var changeCount: Int { board.changeCount }

    public func readCandidate() -> ClipCandidate? {
        let types = board.types ?? []
        let concealed = types.contains(.init("org.nspasteboard.ConcealedType"))
            || types.contains(.init("org.nspasteboard.AutoGeneratedType"))
        let transient = types.contains(.init("org.nspasteboard.TransientType"))
        let fileURLs = (board.readObjects(forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? []
        let text = board.string(forType: .string)
        // Read image bytes whenever there's no file URL, even if text is
        // also present (e.g. browser "Copy Image" pairs image bytes with
        // the image's URL as text). Image-vs-text precedence is a store
        // decision (see ClipStore.ingest), not a pasteboard-reading one.
        let imageData = fileURLs.isEmpty
            ? (board.data(forType: .png) ?? board.data(forType: .tiff)) : nil
        let source = NSWorkspace.shared.frontmostApplication
        return ClipCandidate(
            text: text, imageData: imageData, fileURLs: fileURLs,
            sourceBundleID: source?.bundleIdentifier,
            sourceAppName: source?.localizedName,
            isConcealed: concealed, isTransient: transient)
    }
}
#endif
